# Mini Project 5-1 Explore Descriptive Statistics with Python

## **Introduction**

Data professionals often use descriptive statistics to understand the data they are working with and provide collaborators with a summary of the relative location of values in the data, as well an information about its spread. 

For this activity, you are a member of an analytics team for the United States Environmental Protection Agency (EPA). You are assigned to analyze data on air quality with respect to carbon monoxide, a major air pollutant. The data includes information from more than 200 sites, identified by state, county, city, and local site names. You will use Python functions to gather statistics about air quality, then share insights with stakeholders.

## **Step 1: Imports**

Import the relevant Python libraries `pandas` and `numpy`.

In [4]:
# Import relevant Python libraries.

import pandas as pd
import numpy as np

The dataset provided is in the form of a .csv file named `c4_epa_air_quality.csv`. It contains a susbet of data from the U.S. EPA. As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this Project. Please continue with this activity by completing the following instructions.

In [5]:
# RUN THIS CELL TO IMPORT YOUR DATA.

### YOUR CODE HERE
# Display the first five rows of the dataset
df = pd.read_csv("c4_epa_air_quality.csv")
df.head()

,Unnamed: 0,date_local,state_name,county_name,city_name,local_site_name,parameter_name,units_of_measure,arithmetic_mean,aqi
0,0,2018-01-01,Arizona,Maricopa,Buckeye,BUCKEYE,Carbon monoxide,Parts per million,0.473684,7
1,1,2018-01-01,Ohio,Belmont,Shadyside,Shadyside,Carbon monoxide,Parts per million,0.263158,5
2,2,2018-01-01,Wyoming,Teton,Not in a city,Yellowstone National Park - Old Faithful Snow ...,Carbon monoxide,Parts per million,0.111111,2
3,3,2018-01-01,Pennsylvania,Philadelphia,Philadelphia,North East Waste (NEW),Carbon monoxide,Parts per million,0.300000,3
4,4,2018-01-01,Iowa,Polk,Des Moines,CARPENTER,Carbon monoxide,Parts per million,0.215789,3

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `pandas` library that allows you to read in data from a .csv file and load it into a DataFrame. 

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `read_csv` function from the pandas `library`. The `index_col` parameter can be set to `0` to read in the first column as an index (and to avoid `"Unnamed: 0"` appearing as a column in the resulting DataFrame).

</details>

## **Step 2: Data exploration**

To understand how the dataset is structured, display the first 10 rows of the data.

In [6]:
# Display first 10 rows of the data.

### YOUR CODE HERE

df.head(10)

,Unnamed: 0,date_local,state_name,county_name,city_name,local_site_name,parameter_name,units_of_measure,arithmetic_mean,aqi
0,0,2018-01-01,Arizona,Maricopa,Buckeye,BUCKEYE,Carbon monoxide,Parts per million,0.473684,7
1,1,2018-01-01,Ohio,Belmont,Shadyside,Shadyside,Carbon monoxide,Parts per million,0.263158,5
2,2,2018-01-01,Wyoming,Teton,Not in a city,Yellowstone National Park - Old Faithful Snow ...,Carbon monoxide,Parts per million,0.111111,2
3,3,2018-01-01,Pennsylvania,Philadelphia,Philadelphia,North East Waste (NEW),Carbon monoxide,Parts per million,0.300000,3
4,4,2018-01-01,Iowa,Polk,Des Moines,CARPENTER,Carbon monoxide,Parts per million,0.215789,3
5,5,2018-01-01,Hawaii,Honolulu,Not in a city,Kapolei,Carbon monoxide,Parts per million,0.994737,14
6,6,2018-01-01,Hawaii,Honolulu,Not in a city,Kapolei,Carbon monoxide,Parts per million,0.200000,2
7,7,2018-01-01,Pennsylvania,Erie,Erie,NaN,Carbon monoxide,Parts per million,0.200000,2
8,8,2018-01-01,Hawaii,Honolulu,Honolulu,Honolulu,Carbon monoxide,Parts per million,0.400000,5
9,9,2018-01-01,Colorado,Larimer,Fort Collins,Fort Collins - CSU - S. Mason,Carbon monoxide,Parts per million,0.300000,6

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `pandas` library that allows you to get a specific number of rows from the top of a DataFrame. 

</details>

**Question:** What does the `aqi` column represent?

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `head()` function from the `pandas` library.

</details>

A: Perhaps Air Quality Index

**Question:** In what units are the aqi values expressed?

A: Parts per Million

Now, get a table that contains some descriptive statistics about the data.

In [8]:
# Get descriptive stats.

### YOUR CODE HERE

df.describe()

       Unnamed: 0  arithmetic_mean         aqi
count  260.000000       260.000000  260.000000
mean   129.500000         0.403169    6.757692
std     75.199734         0.317902    7.061707
min      0.000000         0.000000    0.000000
25%     64.750000         0.200000    2.000000
50%    129.500000         0.276315    5.000000
75%    194.250000         0.516009    9.000000
max    259.000000         1.921053   50.000000

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `pandas` library that allows you to generate a table of basic descriptive statistics about the numeric columns in a DataFrame.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `describe()` function from the `pandas` library.

</details>

**Question:** Based on the table of descriptive statistics, what do you notice about the count value for the `aqi` column?

A: That it is 260 which is the same as the other columns and hence there are no missing values

**Question:** What do you notice about the 25th percentile for the `aqi` column?

This is an important measure for understanding where the aqi values lie.

A: It is 2 which is closer to the 50th percentile than the 75th percentile is to the 50th percentile. Hence a slight rightward skew

**Question:** What do you notice about the 75th percentile for the `aqi` column?

This is another important measure for understanding where the aqi values lie.

A: It is 9 which is 4 away from the median which is more than than how much the 25th percentile is from the median which is 3. hence a rightward skew

## **Step 3: Statistical tests**

Next, get some descriptive statistics about the states in the data.

In [10]:
# Get descriptive stats about the states in the data.

### YOUR CODE HERE

df.groupby('state_name').describe()

                     Unnamed: 0                                                \
                          count        mean         std    min     25%    50%
state_name
Alabama                     1.0   71.000000         NaN   71.0   71.00   71.0
Alaska                      2.0  240.500000    3.535534  238.0  239.25  240.5
Arizona                    14.0  131.714286   88.793995    0.0   67.50  140.5
Arkansas                    1.0  186.000000         NaN  186.0  186.00  186.0
California                 66.0  137.272727   69.667020   16.0   76.25  144.0
Colorado                    9.0  119.333333   80.614825    9.0   56.00   97.0
Connecticut                 4.0  119.250000   94.757146   15.0   82.50  108.5
Delaware                    1.0  135.000000         NaN  135.0  135.00  135.0
District Of Columbia        2.0  219.000000   50.911688  183.0  201.00  219.0
Florida                    12.0  149.000000   66.311935   39.0  109.00  153.0
Georgia                     2.0  139.000000  125.865007   50.0   94.50  139.0
Hawaii                      3.0    6.333333    1.527525    5.0    5.50    6.0
Idaho                       2.0   96.000000   82.024387   38.0   67.00   96.0
Illinois                    3.0  127.000000   86.156834   28.0   98.00  168.0
Indiana                     5.0  135.600000   92.629909   11.0   68.00  164.0
Iowa                        3.0   28.333333   28.711206    4.0   12.50   21.0
Kansas                      1.0   29.000000         NaN   29.0   29.00   29.0
Kentucky                    3.0  148.000000   94.873600   84.0   93.50  103.0
Louisiana                   1.0  152.000000         NaN  152.0  152.00  152.0
Maine                       2.0  108.500000  101.116270   37.0   72.75  108.5
Maryland                    4.0  105.000000   82.732501   30.0   66.00   83.5
Massachusetts               4.0   94.000000   58.109093   36.0   48.00   97.5
Michigan                    9.0  172.666667   64.625846   65.0  123.00  192.0
Minnesota                   7.0   94.142857   82.197787   10.0   33.00   73.0
Mississippi                 1.0  160.000000         NaN  160.0  160.00  160.0
Missouri                    3.0   72.333333   59.534304   14.0   42.00   70.0
Montana                     2.0  121.500000    9.192388  115.0  118.25  121.5
Nebraska                    2.0  162.000000  135.764502   66.0  114.00  162.0
Nevada                      4.0   55.500000   40.796242   17.0   23.00   52.5
New Hampshire               2.0  163.500000   24.748737  146.0  154.75  163.5
New Jersey                  6.0  106.666667   55.913028   32.0   64.75  113.0
New Mexico                  2.0  199.500000   53.033009  162.0  180.75  199.5
New York                   10.0  165.800000   43.898367   90.0  134.75  177.5
North Carolina              4.0  127.000000   92.372435   54.0   69.00   97.5
North Dakota                1.0  108.000000         NaN  108.0  108.00  108.0
Ohio                       12.0  128.666667   96.437765    1.0   43.75  134.5
Oklahoma                    4.0  131.750000   49.473057   85.0   91.00  133.5
Oregon                      2.0  215.500000   53.033009  178.0  196.75  215.5
Pennsylvania               10.0  103.200000   75.271066    3.0   67.75   96.5
Puerto Rico                 1.0  187.000000         NaN  187.0  187.00  187.0
Rhode Island                2.0   83.500000   85.559921   23.0   53.25   83.5
South Carolina              1.0  221.000000         NaN  221.0  221.00  221.0
South Dakota                1.0   53.000000         NaN   53.0   53.00   53.0
Tennessee                   2.0  127.000000  110.308658   49.0   88.00  127.0
Texas                      10.0  138.900000   71.242076   24.0   93.75  125.5
Utah                        3.0  171.666667   50.332230  125.0  145.00  165.0
Vermont                     3.0  100.666667   55.048463   47.0   72.50   98.0
Virginia                    4.0   93.250000   78.014422   20.0   38.00   80.0
Washington                  2.0  159.000000  123.036580   72.0  115.50  159.0
West Virginia               1.0   55.000000         NaN   55.0   55.00   55.0
Wisconsin                   1.0  256.000000         NaN  256.0  256.00  256.0
Wyoming                     3.0   67.333333   59.374518    2.0   42.00   82.0

                                    arithmetic_mean            ...            \
                         75%    max           count      mean  ...       75%
state_name                                                     ...
Alabama                71.00   71.0             1.0  0.200000  ...  0.200000
Alaska                241.75  243.0             2.0  0.555264  ...  0.556579
Arizona               204.50  254.0            14.0  0.671804  ...  0.934210
Arkansas              186.00  186.0             1.0  0.300000  ...  0.300000
California            198.75  250.0            66.0  0.684871  ...  0.971491
Colorado              179.00  251.0             9.0  0.330994  ...  0.342105
Connecticut           145.25  245.0             4.0  0.200000  ...  0.231944
Delaware              135.00  135.0             1.0  0.215789  ...  0.215789
District Of Columbia  237.00  255.0             2.0  0.222222  ...  0.233333
Florida               204.25  232.0            12.0  0.299123  ...  0.353947
Georgia               183.50  228.0             2.0  0.286842  ...  0.330263
Hawaii                  7.00    8.0             3.0  0.531579  ...  0.697369
Idaho                 125.00  154.0             2.0  0.621053  ...  0.755263
Illinois              176.50  185.0             3.0  0.254386  ...  0.310527
Indiana               216.00  219.0             5.0  0.304210  ...  0.300000
Iowa                   40.50   60.0             3.0  0.171930  ...  0.207895
Kansas                 29.00   29.0             1.0  0.136842  ...  0.136842
Kentucky              180.00  257.0             3.0  0.181837  ...  0.191176
Louisiana             152.00  152.0             1.0  0.000000  ...  0.000000
Maine                 144.25  180.0             2.0  0.184210  ...  0.192105
Maryland              122.50  223.0             4.0  0.195833  ...  0.203947
Massachusetts         143.50  145.0             4.0  0.225000  ...  0.252632
Michigan              226.00  248.0             9.0  0.465400  ...  0.516667
Minnesota             149.00  212.0             7.0  0.178947  ...  0.223684
Mississippi           160.00  160.0             1.0  0.200000  ...  0.200000
Missouri              101.50  133.0             3.0  0.211111  ...  0.216667
Montana               124.75  128.0             2.0  0.172222  ...  0.208333
Nebraska              210.00  258.0             2.0  0.324416  ...  0.372734
Nevada                 85.00  100.0             4.0  0.988158  ...  1.228947
New Hampshire         172.25  181.0             2.0  0.200000  ...  0.200000
New Jersey            153.75  166.0             6.0  0.302397  ...  0.428840
New Mexico            218.25  237.0             2.0  0.239474  ...  0.243421
New York              192.25  234.0            10.0  0.233684  ...  0.268421
North Carolina        155.50  259.0             4.0  0.191667  ...  0.200000
North Dakota          108.00  108.0             1.0  0.200000  ...  0.200000
Ohio                  219.00  252.0            12.0  0.225379  ...  0.265790
Oklahoma              174.25  175.0             4.0  0.171930  ...  0.221053
Oregon                234.25  253.0             2.0  0.152632  ...  0.178947
Pennsylvania          128.75  235.0            10.0  0.239458  ...  0.300000
Puerto Rico           187.00  187.0             1.0  0.336842  ...  0.336842
Rhode Island          113.75  144.0             2.0  0.302941  ...  0.354411
South Carolina        221.00  221.0             1.0  0.100000  ...  0.100000
South Dakota           53.00   53.0             1.0  0.242105  ...  0.242105
Tennessee             166.00  205.0             2.0  0.192105  ...  0.238158
Texas                 195.00  247.0            10.0  0.198947  ...  0.223684
Utah                  195.00  225.0             3.0  0.461306  ...  0.528801
Vermont               127.50  157.0             3.0  0.227778  ...  0.291666
Virginia              135.25  193.0             4.0  0.277632  ...  0.375000
Washington            202.50  246.0             2.0  0.328948  ...  0.356579
West Virginia          55.00   55.0             1.0  0.226316  ...  0.226316
Wisconsin             256.00  256.0             1.0  0.200000  ...  0.200000
Wyoming               100.00  118.0             3.0  0.134473  ...  0.155556

                                 aqi                                          \
                           max count       mean        std  min    25%   50%
state_name
Alabama               0.200000   1.0   2.000000        NaN  2.0   2.00   2.0
Alaska                0.557895   2.0   8.500000   0.707107  8.0   8.25   8.5
Arizona               1.921053  14.0  15.214286  14.104983  2.0   5.50  10.0
Arkansas              0.300000   1.0   3.000000        NaN  3.0   3.00   3.0
California            1.742105  66.0  12.121212   7.301244  1.0   7.00  11.0
Colorado              0.478947   9.0   5.000000   1.322876  3.0   5.00   5.0
Connecticut           0.261111   4.0   3.500000   1.914854  1.0   2.50   4.0
Delaware              0.215789   1.0   3.000000        NaN  3.0   3.00   3.0
District Of Columbia  0.244444   2.0   2.500000   0.707107  2.0   2.25   2.5
Florida               0.600000  12.0   5.500000   2.430862  1.0   4.50   6.0
Georgia               0.373684   2.0   4.000000   2.828427  2.0   3.00   4.0
Hawaii                0.994737   3.0   7.000000   6.244998  2.0   3.50   5.0
Idaho                 0.889474   2.0  10.000000   5.656854  6.0   8.00  10.0
Illinois              0.421053   3.0   3.333333   2.309401  2.0   2.00   2.0
Indiana               0.542105   5.0   3.800000   2.387467  2.0   3.00   3.0
Iowa                  0.215789   3.0   2.000000   1.000000  1.0   1.50   2.0
Kansas                0.136842   1.0   2.000000        NaN  2.0   2.00   2.0
Kentucky              0.200000   3.0   2.000000   0.000000  2.0   2.00   2.0
Louisiana             0.000000   1.0   0.000000        NaN  0.0   0.00   0.0
Maine                 0.200000   2.0   2.500000   0.707107  2.0   2.25   2.5
Maryland              0.215789   4.0   2.250000   0.500000  2.0   2.00   2.0
Massachusetts         0.252632   4.0   2.750000   0.500000  2.0   2.75   3.0
Michigan              0.811111   9.0   8.111111   3.257470  2.0   7.00   8.0
Minnesota             0.273684   7.0   2.142857   0.690066  1.0   2.00   2.0
Mississippi           0.200000   1.0   2.000000        NaN  2.0   2.00   2.0
Missouri              0.233333   3.0   3.000000   1.732051  2.0   2.00   2.0
Montana               0.244444   2.0   2.000000   1.414214  1.0   1.50   2.0
Nebraska              0.421053   2.0   7.000000   2.828427  5.0   6.00   7.0
Nevada                1.805263   4.0  18.500000  15.351439  7.0  10.00  13.0
New Hampshire         0.200000   2.0   2.000000   0.000000  2.0   2.00   2.0
New Jersey            0.500000   6.0   4.333333   1.966384  2.0   3.00   4.0
New Mexico            0.247368   2.0   6.000000   1.414214  5.0   5.50   6.0
New York              0.300000  10.0   2.500000   0.527046  2.0   2.00   2.5
North Carolina        0.200000   4.0   2.000000   0.000000  2.0   2.00   2.0
North Dakota          0.200000   1.0   2.000000        NaN  2.0   2.00   2.0
Ohio                  0.394737  12.0   3.333333   1.302678  2.0   2.75   3.0
Oklahoma              0.284211   4.0   2.500000   1.732051  1.0   1.75   2.0
Oregon                0.205263   2.0   2.000000   1.414214  1.0   1.50   2.0
Pennsylvania          0.455556  10.0   2.900000   1.663330  0.0   2.00   3.0
Puerto Rico           0.336842   1.0   5.000000        NaN  5.0   5.00   5.0
Rhode Island          0.405882   2.0   4.000000   2.828427  2.0   3.00   4.0
South Carolina        0.100000   1.0   1.000000        NaN  1.0   1.00   1.0
South Dakota          0.242105   1.0   5.000000        NaN  5.0   5.00   5.0
Tennessee             0.284211   2.0   2.000000   1.414214  1.0   1.50   2.0
Texas                 0.252632  10.0   2.700000   0.948683  2.0   2.00   2.5
Utah                  0.694444   3.0   9.000000   1.732051  7.0   8.50  10.0
Vermont               0.350000   3.0   3.333333   2.516611  1.0   2.00   3.0
Virginia              0.442105   4.0   4.000000   2.581989  1.0   2.50   4.0
Washington            0.384211   2.0   4.000000   1.414214  3.0   3.50   4.0
West Virginia         0.226316   1.0   3.000000        NaN  3.0   3.00   3.0
Wisconsin             0.200000   1.0   2.000000        NaN  2.0   2.00   2.0
Wyoming               0.200000   3.0   1.666667   0.577350  1.0   1.50   2.0


                        75%   max
state_name
Alabama                2.00   2.0
Alaska                 8.75   9.0
Arizona               19.75  50.0
Arkansas               3.00   3.0
California            16.00  40.0
Colorado               6.00   7.0
Connecticut            5.00   5.0
Delaware               3.00   3.0
District Of Columbia   2.75   3.0
Florida                7.00   9.0
Georgia                5.00   6.0
Hawaii                 9.50  14.0
Idaho                 12.00  14.0
Illinois               4.00   6.0
Indiana                3.00   8.0
Iowa                   2.50   3.0
Kansas                 2.00   2.0
Kentucky               2.00   2.0
Louisiana              0.00   0.0
Maine                  2.75   3.0
Maryland               2.25   3.0
Massachusetts          3.00   3.0
Michigan              10.00  13.0
Minnesota              2.50   3.0
Mississippi            2.00   2.0
Missouri               3.50   5.0
Montana                2.50   3.0
Nebraska               8.00   9.0
Nevada                21.50  41.0
New Hampshire          2.00   2.0
New Jersey             5.75   7.0
New Mexico             6.50   7.0
New York               3.00   3.0
North Carolina         2.00   2.0
North Dakota           2.00   2.0
Ohio                   3.50   6.0
Oklahoma               2.75   5.0
Oregon                 2.50   3.0
Pennsylvania           3.00   6.0
Puerto Rico            5.00   5.0
Rhode Island           5.00   6.0
South Carolina         1.00   1.0
South Dakota           5.00   5.0
Tennessee              2.50   3.0
Texas                  3.00   5.0
Utah                  10.00  10.0
Vermont                4.50   6.0
Virginia               5.50   7.0
Washington             4.50   5.0
West Virginia          3.00   3.0
Wisconsin              2.00   2.0
Wyoming                2.00   2.0

[52 rows x 24 columns]

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `pandas` library that allows you to generate basic descriptive statistics about a DataFrame or a column you are interested in.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

 Use the `describe()` function from the `pandas` library. Note that this function can be used:
- "on a DataFrame (to find descriptive statistics about the numeric columns)" 
- "directly on a column containing categorical data (to find pertinent descriptive statistics)"

</details>

**Question:** What do you notice while reviewing the descriptive statistics about the states in the data? 

Note: Sometimes you have to individually calculate statistics. To review to that approach, use the `numpy` library to calculate each of the main statistics in the preceding table for the `aqi` column.

A: Some states have missing std values. Also the mean and median of different states are very away from other states indicating incosistent aqi ratings

## **Step 4. Results and evaluation**

Now, compute the mean value from the `aqi` column.

In [14]:
# Compute the mean value from the aqi column.

### YOUR CODE HERE

mean_aqi = df['aqi'].mean()

print("Mean AQI:", mean_aqi)

Mean AQI: 6.757692307692308

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `numpy` library that allows you to get the mean value from an array or a Series of values.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `mean()` function from the `numpy` library.

</details>

**Question:** What do you notice about the mean value from the `aqi` column?

This is an important measure, as it tells you what the average air quality is based on the data.

A: It is quite low compared to the range in the values

Next, compute the median value from the aqi column.

In [15]:
# Compute the median value from the aqi column.

### YOUR CODE HERE

median_aqi = df['aqi'].median()

print("Median AQI:", median_aqi)

Median AQI: 5.0

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `numpy` library that allows you to get the median value from an array or a series of values.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `median()` function from the `numpy` library.

</details>

**Question:** What do you notice about the median value from the `aqi` column?

This is an important measure for understanding the central location of the data.

A: Slightly lower than the mean implying there are some outlier values to the right

Next, identify the minimum value from the `aqi` column.

In [16]:
# Identify the minimum value from the aqi column.

### YOUR CODE HERE

min_aqi = df['aqi'].min()

print("Min AQI:", min_aqi)

Min AQI: 0

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `numpy` library that allows you to get the minimum value from an array or a Series of values.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `min()` function from the `numpy` library.

</details>

**Question:** What do you notice about the minimum value from the `aqi` column?

This is an important measure, as it tell you the best air quality observed in the data.

The minimum value for the aqi column is 0. This means that the smallest aqi value in the data is 0 parts per million.

Now, identify the maximum value from the `aqi` column.

In [17]:
# Identify the maximum value from the aqi column.

### YOUR CODE HERE
max_aqi = df['aqi'].max()

print("Max AQI:", max_aqi)

Max AQI: 50

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `numpy` library that allows you to get the maximum value from an array or a Series of values.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

  Use the `max()` function from the `numpy` library.

</details>

**Question:** What do you notice about the maximum value from the `aqi` column?

This is an important measure, as it tells you which value in the data corresponds to the worst air quality observed in the data.

A: This is 50 which means that some outliers exist and there are very far from the mean

Now, compute the standard deviation for the `aqi` column.

By default, the `numpy` library uses 0 as the Delta Degrees of Freedom, while `pandas` library uses 1. To get the same value for standard deviation using either library, specify the `ddof` parameter to 1 when calculating standard deviation.

In [18]:
# Compute the standard deviation for the aqi column.

### YOUR CODE HERE

std_aqi = df['aqi'].std()

print("Std AQI:", std_aqi)

Std AQI: 7.061706678820724

<details>
  <summary><h4><strong>Hint 1</strong></h4></summary>

  There is a function in the `numpy` library that allows you to get the standard deviation from an array or a series of values.

</details>

<details>
  <summary><h4><strong>Hint 2</strong></h4></summary>

Use the `std()` function from the `numpy` library. Make sure to specify the `ddof` parameter as 1. To read more about this function,  refer to its documentation in the references section of this lab.

</details>

**Question:** What do you notice about the standard deviation for the `aqi` column? 

This is an important measure of how spread out the aqi values are.

A: Fairly high standard deviation which means they are somewhat spread out

## **Considerations**

**What are some key takeaways that you learned during this Project?**

A: That it is fairly easy to use different functions to analyze a dataset

**How would you present your findings from this Project to others? Consider the following relevant points noted by AirNow.gov as you respond:**
- "AQI values at or below 100 are generally thought of as satisfactory. When AQI values are above 100, air quality is considered to be unhealthy—at first for certain sensitive groups of people, then for everyone as AQI values increase."
- "An AQI of 100 for carbon monoxide corresponds to a level of 9 parts per million."

A: I would list the AQis of different staes and then talk about the aggregate descriptor AQI of the entire data set. Mention min, 25th percentile, median, and 75th percentile, and max, and mention the units being parts per million.

**What summary would you provide to readers? Use the same information provided previously from AirNow.gov as you respond.**

A: The Air Quality Index (AQI) data shoes a range of air quality levels across different states. The lowest recorded AQI value is 0 while the highest reaches 50. The Median is 5. According to AirNOw.gov, AQI values above 100 indicate unhealthy air quality, particular for sensitive groups at first. If any states have an AQI above 100, there might be health risks associated

Additionally, an AQI of 100 for carbon monoxide corresponds to 9 parts per million.

**References**

[Air Quality Index - A Guide to Air Quality and Your Health](https://www.airnow.gov/sites/default/files/2018-04/aqi_brochure_02_14_0.pdf). (2014,February)

[Numpy.Std — NumPy v1.23 Manual](https://numpy.org/doc/stable/reference/generated/numpy.std.html)

US EPA, OAR. (2014, 8 July).[*Air Data: Air Quality Data Collected at Outdoor Monitors Across the US*](https://www.epa.gov/outdoor-air-quality-data).